### ISSUE TITLE
Reconnection process

### ISSUE THREAD

**Issue by jurepetrovic** [Itiviti/simple-slack-api#299]
Hello, 

when slack goes **out of service**, we sometimes get the following Null Pointer Exception: 
`
Stack Trace: java.lang.NullPointerException
        at com.ullink.slack.simpleslackapi.impl.SlackJSONSessionStatusParser.parse(SlackJSONSessionStatusParser.java:71)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:389)
        at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:348)
`

Has anyone any idea how to do reconnection attempt properly here? 

I looked here, but if slack service goes down, we don't get _goodbye_ message.
https://github.com/Itiviti/simple-slack-api/issues/298

Thanks,
Jure

**Comment by ConnorLinfoot** [comment]
This error seems to be due to the RTM change deprecating the previous behavior of `rtm.start` and the new behavior not being supported by this library at the moment

**Comment by jurepetrovic** [comment]
I used try/catch and then slack session builder to create autoreconnect SlackSession. 
It solves the problem where the client loses connection, but not when server drops. 

@ConnorLinfoot 
How would you go about changing this behaviour? Where is rtm.start used? 
What was the change on RTM? 

I got used to simple-slack-api, otherwise works fine for me and is lightweight. 
Would really like to solve this. 

Thanks.
Jure

**Comment by ConnorLinfoot** [comment]
> I used try/catch and then slack session builder to create autoreconnect SlackSession. It solves the problem where the client loses connection, but not when server drops.
> 
> @ConnorLinfoot How would you go about changing this behaviour? Where is rtm.start used? What was the change on RTM?
> 
> I got used to simple-slack-api, otherwise works fine for me and is lightweight. Would really like to solve this.
> 
> Thanks. Jure

Personally I moved to using the official slack java client, I did originally try updating this client but upon realising master seemed to be half updated to the new socket mode system instead of RTM I chose to leave it. Depending on your use case it may be better to also adopt the official client as its more likely to stay up to date and have more support around it (although the documentation is a bit lacking in my opinion)
